# **<font color="red">Accuracy and Confusion Matrix</font>**

## **<font color="blue">Data Visualization</font>**

In [1]:
import pandas as pd

df = pd.read_csv("../data/heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
df.shape

(303, 14)

In [3]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [6]:
df['target'].unique()

array([1, 0], dtype=int64)

In [7]:
y = df['target']
X = df.drop(columns=['target'])

# # if target column is always last column then use this technique
# X = df.iloc[:, :-1]
# y = df.iloc[:, -1]

X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [8]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

## **<font color="blue">Model Predictions and Score</font>**

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("../data/heart.csv")

y = df['target']
X = df.drop(columns=['target'])

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# model
lrc = LogisticRegression()
dtc = DecisionTreeClassifier()

# train
lrc.fit(X_train, y_train)
dtc.fit(X_train, y_train)

# test
y_pred_lrc = lrc.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

print("="*80)
print("Accuracy Score: ")
print("Logistic_Regression_Accuracy: ", accuracy_score(y_test, y_pred_lrc))
print("Decision_Tree_Accuracy: ", accuracy_score(y_test, y_pred_dtc))
print("="*80)
print("="*80)
print("Confusion Matrix: ")
print("Logistic_Regression_Confusion_Matrix: \n", confusion_matrix(y_test, y_pred_lrc))
print("Decision_Tree_Confusion_Matrix: \n", confusion_matrix(y_test, y_pred_dtc))
print("="*80)

================================================================================
Accuracy Score:
Logistic_Regression_Accuracy:  0.8852459016393442
Decision_Tree_Accuracy:  0.8032786885245902
================================================================================
================================================================================
Confusion Matrix:
Logistic_Regression_Confusion_Matrix:
 [[25  4]
 [ 3 29]]
Decision_Tree_Confusion_Matrix:
 [[25  4]
 [ 8 24]]
================================================================================

D:\Study\machineLearning\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## **<font color="green">Classification Score</font>**

In [10]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

print("="*25, "For Logistic Regression Model", "="*25)
print("-"*60)
cdf_lrc = pd.DataFrame(confusion_matrix(y_test, y_pred_lrc), columns=list(range(0, 2)))
print(cdf_lrc)
print("-"*60)
print("Logistic_Regression_Accuracy: ", accuracy_score(y_test, y_pred_lrc))
print("Logistic_Regression_Precision: ", precision_score(y_test, y_pred_lrc))
print("Logistic_Regression_Recall: ", recall_score(y_test, y_pred_lrc))
print("Logistic_Regression_F1_Score: ", f1_score(y_test, y_pred_lrc))
print("-"*60)
print("="*80)
print()

print("="*25, "For Decision Tree Model", "="*25)
print("-"*60)
cdf_dtc = pd.DataFrame(confusion_matrix(y_test, y_pred_dtc), columns=list(range(0, 2)))
print(cdf_dtc)
print("-"*60)
print("Decision_Tree_Accuracy: ", accuracy_score(y_test, y_pred_dtc))
print("Decision_Tree_Precision: ", precision_score(y_test, y_pred_dtc))
print("Decision_Tree_Recall: ", recall_score(y_test, y_pred_dtc))
print("Decision_Tree_F1_Score: ", f1_score(y_test, y_pred_dtc))
print("-"*60)
print("="*80)
print()

========================= For Logistic Regression Model =========================
------------------------------------------------------------
    0   1
0  25   4
1   3  29
------------------------------------------------------------
Logistic_Regression_Accuracy:  0.8852459016393442
Logistic_Regression_Precision:  0.8787878787878788
Logistic_Regression_Recall:  0.90625
Logistic_Regression_F1_Score:  0.8923076923076924
------------------------------------------------------------
================================================================================

========================= For Decision Tree Model =========================
------------------------------------------------------------
    0   1
0  25   4
1   8  24
------------------------------------------------------------
Decision_Tree_Accuracy:  0.8032786885245902
Decision_Tree_Precision:  0.8571428571428571
Decision_Tree_Recall:  0.75
Decision_Tree_F1_Score:  0.8
------------------------------------------------------------
================================================================================

In [11]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

def print_scores(model_name, y_true, y_pred):
    print("="*25, f"For {model_name}", "="*25)
    print("-"*70)

    # confusion matrix
    labels = sorted(list(set(y_true)))
    cdf = pd.DataFrame(confusion_matrix(y_true, y_pred), 
                       columns=[f"Pred_{c}" for c in labels],
                       index=[f"True_{c}" for c in labels])
    print(cdf)
    print("-"*70)

    # accuracy
    print(f"{model_name}_Accuracy: ", accuracy_score(y_true, y_pred))

    # Multiclass-safe metrics
    print(f"{model_name}_Precision (macro): ", precision_score(y_true, y_pred, average='macro'))
    print(f"{model_name}_Precision (weighted): ", precision_score(y_true, y_pred, average='weighted'))
    print(f"{model_name}_Precision (micro): ", precision_score(y_true, y_pred, average='micro'))

    print("-"*40)

    print(f"{model_name}_Recall (macro): ", recall_score(y_true, y_pred, average='macro'))
    print(f"{model_name}_Recall (weighted): ", recall_score(y_true, y_pred, average='weighted'))
    print(f"{model_name}_Recall (micro): ", recall_score(y_true, y_pred, average='micro'))

    print("-"*40)

    print(f"{model_name}_F1 (macro): ", f1_score(y_true, y_pred, average='macro'))
    print(f"{model_name}_F1 (weighted): ", f1_score(y_true, y_pred, average='weighted'))
    print(f"{model_name}_F1 (micro): ", f1_score(y_true, y_pred, average='micro'))

    print("-"*70)
    print("="*90)
    print("\n")


# ---- Print results for both models ----
print_scores("Logistic Regression Model", y_test, y_pred_lrc)
print_scores("Decision Tree Model", y_test, y_pred_dtc)

========================= For Logistic Regression Model =========================
----------------------------------------------------------------------
        Pred_0  Pred_1
True_0      25       4
True_1       3      29
----------------------------------------------------------------------
Logistic Regression Model_Accuracy:  0.8852459016393442
Logistic Regression Model_Precision (macro):  0.8858225108225108
Logistic Regression Model_Precision (weighted):  0.8854765453126109
Logistic Regression Model_Precision (micro):  0.8852459016393442
----------------------------------------
Logistic Regression Model_Recall (macro):  0.8841594827586207
Logistic Regression Model_Recall (weighted):  0.8852459016393442
Logistic Regression Model_Recall (micro):  0.8852459016393442
----------------------------------------
Logistic Regression Model_F1 (macro):  0.8847503373819163
Logistic Regression Model_F1 (weighted):  0.8851220105749872
Logistic Regression Model_F1 (micro):  0.8852459016393442
----------------------------------------------------------------------
==========================================================================================


========================= For Decision Tree Model =========================
----------------------------------------------------------------------
        Pred_0  Pred_1
True_0      25       4
True_1       8      24
----------------------------------------------------------------------
Decision Tree Model_Accuracy:  0.8032786885245902
Decision Tree Model_Precision (macro):  0.8073593073593073
Decision Tree Model_Precision (weighted):  0.8098076786601377
Decision Tree Model_Precision (micro):  0.8032786885245902
----------------------------------------
Decision Tree Model_Recall (macro):  0.8060344827586207
Decision Tree Model_Recall (weighted):  0.8032786885245902
Decision Tree Model_Recall (micro):  0.8032786885245902
----------------------------------------
Decision Tree Model_F1 (macro):  0.8032258064516129
Decision Tree Model_F1 (weighted):  0.8030671602326811
Decision Tree Model_F1 (micro):  0.8032786885245902
----------------------------------------------------------------------
==========================================================================================