In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd

class CustomeLR:
    """
    This is Simple Linear Regression. One Feature One Label.
    It will not work for Multilinear Regression. 
    So do not try for n feature m label.
    """
    def __init__(self):
        self.m = None  # slope/weight
        self.b = None  # intercept/bias

    def fit(self, X_train, y_train):
        if isinstance(X_train, pd.DataFrame):
            X_train = X_train.iloc[:, 0]  # Use first column if DataFrame
        x_mean = X_train.mean()
        y_mean = y_train.mean()

        num = ((X_train - x_mean) * (y_train - y_mean)).sum()
        den = ((X_train - x_mean) ** 2).sum()

        self.m = num / den
        self.b = y_mean - self.m * x_mean
        return self.m, self.b

    def predict(self, X_test):
        if isinstance(X_test, pd.DataFrame):
            X_test = X_test.iloc[:, 0]
        return self.m * X_test + self.b

    def accuracy(self, y_test, y_pred):
        ss_total = ((y_test - y_test.mean()) ** 2).sum()
        ss_residual = ((y_test - y_pred) ** 2).sum()
        r2 = 1 - (ss_residual / ss_total)
        return r2

In [3]:
df = pd.read_csv("../data/placement01.csv")
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [4]:
X = df.iloc[:, 0:1]
y = df.iloc[:, -1]

In [5]:
print(type(X))
X.head()

<class 'pandas.core.frame.DataFrame'>

   cgpa
0  6.89
1  5.12
2  7.82
3  7.42
4  6.94

In [6]:
print(type(y))
y.head()

<class 'pandas.core.series.Series'>

0    3.26
1    1.98
2    3.25
3    3.67
4    3.57
Name: package, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(160, 1) (160,)
(40, 1) (40,)

In [8]:
lr = CustomeLR()
m, b = lr.fit(X_train, y_train)
m, b

(0.557951973425072, -0.8961119222429144)

In [9]:
y_pred = lr.predict(X_test)
y_pred.head()

112    3.891116
29     3.093245
182    2.384646
199    2.574349
193    1.653729
Name: cgpa, dtype: float64

In [10]:
accuracy = lr.accuracy(y_test, y_pred)
accuracy = round(accuracy, 3)
accuracy

0.781